vich_uploader:
    db_driver: mongodb
    mappings:
        firma_logo:
            uri_prefix: /uploads/firma_logo
            upload_destination: '%kernel.project_dir%/public/uploads/firma_logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
