controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
# config/routes.yaml

firma_lista:
    path: /firmaLista
    controller: App\Controller\FirmaController::listaFirme
    methods: GET

firma_adauga:
    path: /firma/adauga
    controller: App\Controller\FirmaController::adaugaFirma
    methods: [GET, POST]

firma_vezi:
    path: /firma/{id}
    controller: App\Controller\FirmaController::veziFirma
    methods: GET

firma_editare:
    path: /firma/editare/{id}
    controller: App\Controller\FirmaController::editareFirma
    methods: [GET, POST]

firma_sterge:
    path: /firma/sterge/{id}
    controller: App\Controller\FirmaController::stergeFirma
    methods: [GET, POST]

firma_top_views:
    path: /firme/top-views
    controller: App\Controller\FirmaController::topViewedFirms
    methods: ['GET']

increment_view:
    path: /firma/{id}/increment-view
    controller: App\Controller\FirmaController::incrementView
    methods: ['GET']

firmaStergeConfirma:
    path: /firma/sterge-confirma/{id}
    controller: App\Controller\FirmaController::stergeFirmaConfirma


